### PR TITLE
Implement adapter Name and add Name constant

### PR DESCRIPTION
**Pull request by lafriks**

### CODE REVIEW

**Comment by Fs02** [comment]
can you fix the code coverage?

**Comment by Fs02** [comment]
you can do unit test trick like extracting the panic checking code
it's easier to maintain 100% coverage than just letting it drops

**Comment by lafriks** [comment]
I don't see reason to simulate code coverage percentage when actual case is not really checked

**Comment by Fs02** [comment]
it's to maintain code coverage
easier to enforce 100% code coverage policy than allowing coverage to be dropped case by case

what we do here is unit test, so IMO it's acceptable to do that, in fact we should make the code unit testable and sometimes it's required repeated refactoring

we must do actual case test when we are responsible for the logic, but for opening connection and etc, it's implemented by driver (and they are responsible for it) so it's okay to just simulate it

**Comment by Fs02** [comment]
IMO, this is not much different than when we mock functions to do unit test

**Comment by lafriks** [comment]
Fixed it a bit different by mocking db.Open and this way actually kind a testing that code path

**Review by Fs02 — APPROVED** [review]
LGTM, Thanks
I really appreciate this

**Pull request merged**
